export interface ConfigurationStr {
  PublicInterface:    		string;
  BackendPort:          	string;
  FrontendPort: 	        string;
  WebSocketPort: 	        string;
  StartContainers:     		string;
  MaxContainers:            string;
  OperationMode:        	string;
  NodeMode:             	string;
  ClusterName: 	         	string;
  ClusterPassword:  		string;
  HostUser:       	 		string;
  HostPassword:     		string;
  SelfRegistration:   		string;
  CodeExecTimeout:          string;
  CodeMaxFileSize:          string;
  Queue:                    string;
  MaxConcurrency:           string;
  Debug:         			string;
  Error:           			string;
  SmtpServer: 				string;
  SmtpPort: 				string;
  SmtpUser: 				string;
  SmtpPassword: 			string;
  DbUser: 				    string;
  DbPassword: 				string;
  DbPort: 				    string;
  DbHost: 			        string;
}
